package ru.genesiscorporation.workspace.beta.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class WorkspaceColorsPalette(
    val background: Color = Color.Unspecified,
    val surface: Color = Color.Unspecified,
    val primary: Color = Color.Unspecified,
    val onPrimary: Color = Color.Unspecified,
    val textHeaders: Color = Color.Unspecified,
    val textAdditional50: Color = Color.Unspecified,
    val textAdditional30: Color = Color.Unspecified,
    val iconBase: Color = Color.Unspecified,
    val iconDisable: Color = Color.Unspecified,
    val iconHover: Color = Color.Unspecified,
    val iconActive: Color = Color.Unspecified,
    val messageBackground: Color = Color.Unspecified,
    val messageTimeColor: Color = Color.Unspecified,
    val messageOwnBackground: Color = Color.Unspecified,
    val messageActiveCallBackground: Color = Color.Unspecified,
    val messageSelectedForeground: Color = Color.Unspecified,
    val cardBackgroundBase: Color = Color.Unspecified,
    val cardBackgroundActive: Color = Color.Unspecified,
    val infoCardBackground: Color = Color.Unspecified,
    val noticeBase: Color = Color.Unspecified,
    val noticeDisable: Color = Color.Unspecified,
    val noticeOnBadge: Color = Color.Unspecified,
    val noticeCounterBadge: Color = Color.Unspecified,
    val searchBackground: Color = Color.Unspecified,
    val indicatorYellow: Color = Color.Unspecified,
    val indicatorPink: Color = Color.Unspecified,
    val indicatorPurple: Color = Color.Unspecified,
    val indicatorOrange: Color = Color.Unspecified,
    val indicatorGreen: Color = Color.Unspecified,
    val indicatorRed: Color = Color.Unspecified,
    val indicatorBlue: Color = Color.Unspecified,
    val indicatorGrey: Color = Color.Unspecified,
    val chatHeaderBackground: Color = Color.Unspecified
)

val LightWorkspaceColorsPalette = WorkspaceColorsPalette(
    background = Color(color = 0xFFF6F6F8),
    surface = Color(color = 0xFFFFFFFF),
    primary = Color(color = 0xFFE96520),
    onPrimary = Color(color = 0xFF1B1B1D),
    textHeaders = Color(color = 0xFF1B1B1D),
    textAdditional50 = Color(color = 0xFF6D6D72),
    textAdditional30 = Color(color = 0xFF9A9A9F),
    iconBase = Color(color = 0xFF77777C),
    iconDisable = Color(color = 0xFFC6C6CA),
    iconHover = Color(color = 0xFFFFE6D7),
    iconActive = Color(color = 0xFF1B1B1D),
    messageBackground = Color(color = 0xFFFFFFFF),
    messageTimeColor = Color(color = 0xFF8B8B90),
    messageOwnBackground = Color(color = 0xFFF0E1D5),
    messageActiveCallBackground = Color(color = 0xFFE7F5EA),
    messageSelectedForeground = Color(color = 0xFF23A047),
    cardBackgroundBase = Color(color = 0xFFFFFFFF),
    cardBackgroundActive = Color(color = 0xFFE7E7EA),
    infoCardBackground = Color(color = 0xFFFFFFFF),
    noticeBase = Color(color = 0xFFFF1420),
    noticeDisable = Color(color = 0xFF8B8B90),
    noticeOnBadge = Color(color = 0xFFFFFFFF),
    noticeCounterBadge = Color(color = 0xFFFF1420),
    searchBackground = Color(color = 0xFFEEEEF0),
    indicatorYellow = Color(color = 0xFFFFC400),
    indicatorPink = Color(color = 0xFFF458D2),
    indicatorPurple = Color(color = 0xFF8D6DFF),
    indicatorOrange = Color(color = 0xFFFF7A00),
    indicatorGreen = Color(color = 0xFF26C038),
    indicatorRed = Color(color = 0xFFE43535),
    indicatorBlue = Color(color = 0xFF4B98E6),
    indicatorGrey = Color(color = 0xFF77777C),
    chatHeaderBackground = Color(color = 0xFFF0F0F2),
)

val DarkWorkspaceColorsPalette = WorkspaceColorsPalette(
    background = Color(color = 0xFF1B1B1D),
    surface = Color(color = 0xFF202022),
    primary = Color(color = 0xFFFF8138),
    onPrimary = Color(color = 0xFF1B1B1D),
    textHeaders = Color(color = 0xFFF8F8F9),
    textAdditional50 = Color(color = 0xFF9A9A9F),
    textAdditional30 = Color(color = 0xFF707075),
    iconBase = Color(color = 0xFF77777C),
    iconDisable = Color(color = 0xFF4D4D51),
    iconHover = Color(color = 0xFF99999E),
    iconActive = Color(color = 0xFFF8F8F9),
    messageBackground = Color(color = 0xFF353537),
    messageTimeColor = Color(color = 0xFF9A9A9F),
    messageOwnBackground = Color(color = 0xFF4E392B),
    messageActiveCallBackground = Color(color = 0xFF183421),
    messageSelectedForeground = Color(color = 0xFF26C073),
    cardBackgroundBase = Color(color = 0xFF202022),
    cardBackgroundActive = Color(color = 0xFF353537),
    infoCardBackground = Color(color = 0xFF373737),
    noticeBase = Color(color = 0xFFFF1420),
    noticeDisable = Color(color = 0xFF66666A),
    noticeOnBadge = Color(color = 0xFFFFFFFF),
    noticeCounterBadge = Color(color = 0xFFFF1420),
    searchBackground = Color(color = 0xFF262628),
    indicatorYellow = Color(color = 0xFFFFCC00),
    indicatorPink = Color(color = 0xFFF458D2),
    indicatorPurple = Color(color = 0xFF9A7BFF),
    indicatorOrange = Color(color = 0xFFFF7A00),
    indicatorGreen = Color(color = 0xFF26C038),
    indicatorRed = Color(color = 0xFFFF4248),
    indicatorBlue = Color(color = 0xFF51ABFF),
    indicatorGrey = Color(color = 0xFF77777C),
    chatHeaderBackground = Color(color = 0xFF353537),
)

val LocalWorkspaceColorsPalette = staticCompositionLocalOf { WorkspaceColorsPalette() }
