package ru.genesiscorporation.workspace.beta.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class WorkspaceColorsPalette(
    val background: Color = Color.Unspecified,
    val surface: Color = Color.Unspecified,
    val primary: Color = Color.Unspecified,
    val onPrimary: Color = Color.Unspecified,
    val textHeaders: Color = Color.Unspecified,
    val textAdditional50: Color = Color.Unspecified,
    val textAdditional30: Color = Color.Unspecified,
    val iconBase: Color = Color.Unspecified,
    val iconDisable: Color = Color.Unspecified,
    val iconHover: Color = Color.Unspecified,
    val iconActive: Color = Color.Unspecified,
    val messageBackground: Color = Color.Unspecified,
    val messageTimeColor: Color = Color.Unspecified,
    val messageOwnBackground: Color = Color.Unspecified,
    val messageActiveCallBackground: Color = Color.Unspecified,
    val messageSelectedForeground: Color = Color.Unspecified,
    val cardBackgroundBase: Color = Color.Unspecified,
    val cardBackgroundActive: Color = Color.Unspecified,
    val noticeBase: Color = Color.Unspecified,
    val noticeDisable: Color = Color.Unspecified,
    val noticeOnBadge: Color = Color.Unspecified,
    val noticeCounterBadge: Color = Color.Unspecified,
    val searchBackground: Color = Color.Unspecified,
    val mentionSuggestionsBackground: Color = Color.Unspecified,
    val indicatorYellow: Color = Color.Unspecified,
    val indicatorPink: Color = Color.Unspecified,
    val indicatorPurple: Color = Color.Unspecified,
    val indicatorOrange: Color = Color.Unspecified,
    val indicatorGreen: Color = Color.Unspecified,
    val indicatorRed: Color = Color.Unspecified,
    val indicatorBlue: Color = Color.Unspecified,
    val indicatorGrey: Color = Color.Unspecified,
    val chatHeaderBackground: Color = Color.Unspecified,
    val divider: Color = Color.Unspecified
)

val LightWorkspaceColorsPalette = WorkspaceColorsPalette(
    background = Color(color = 0xFFE4ECF3),
    surface = Color(color = 0xFFFFFFFF),
    primary = Color(color = 0xFF7087FF),
    onPrimary = Color(color = 0xFF1B1B1D),
    textHeaders = Color(color = 0xFF1B1B1D),
    textAdditional50 = Color(color = 0xFF787878),
    textAdditional30 = Color(color = 0xFF989898),
    iconBase = Color(color = 0xFF989898),
    iconDisable = Color(color = 0xFF474747),
    iconHover = Color(color = 0xFFCDE6FF),
    iconActive = Color(color = 0xFF1B1B1D),
    messageBackground = Color(color = 0xFFFFFFFF),
    messageTimeColor = Color(color = 0xFF989898),
    messageOwnBackground = Color(color = 0xFFAED7FF),
    messageActiveCallBackground = Color(color = 0xFFE2FFE9),
    messageSelectedForeground = Color(color = 0xFFA8E6AF),
    cardBackgroundBase = Color(color = 0xFFCDE6FF),
    cardBackgroundActive = Color(color = 0xFFCDE6FF),
    noticeBase = Color(color = 0xFF7087FF),
    noticeDisable = Color(color = 0xFF989898),
    noticeOnBadge = Color(color = 0xFFFFFFFF),
    noticeCounterBadge = Color(color = 0xFF7087FF),
    searchBackground = Color(color = 0xFFFFFFFF),
    mentionSuggestionsBackground = Color(color = 0xFFF5F5F5),
    indicatorYellow = Color(color = 0xFFFFD633),
    indicatorPink = Color(color = 0xFFF458D2),
    indicatorPurple = Color(color = 0xFF8D6DFF),
    indicatorOrange = Color(color = 0xFFFF8900),
    indicatorGreen = Color(color = 0xFF26C038),
    indicatorRed = Color(color = 0xFFE43535),
    indicatorBlue = Color(color = 0xFF4B98E6),
    indicatorGrey = Color(color = 0xFF484848),
    chatHeaderBackground = Color(color = 0xFFEAF5FF),
    divider = Color(color = 0xFFC5CED8)
)

val DarkWorkspaceColorsPalette = WorkspaceColorsPalette(
    background = Color(color = 0xFF141517),
    surface = Color(color = 0xFF222328),
    primary = Color(color = 0xFF7087FF),
    onPrimary = Color(color = 0xFF141517),
    textHeaders = Color(color = 0xFFFFFFFF),
    textAdditional50 = Color(color = 0xFF999999),
    textAdditional30 = Color(color = 0xFF707070),
    iconBase = Color(color = 0xFF707070),
    iconDisable = Color(color = 0xFF474747),
    iconHover = Color(color = 0xFF999999),
    iconActive = Color(color = 0xFFFFFFFF),
    messageBackground = Color(color = 0xFF333333),
    messageTimeColor = Color(color = 0xFF999999),
    messageOwnBackground = Color(color = 0xFF252942),
    messageActiveCallBackground = Color(color = 0xFF1B3027),
    messageSelectedForeground = Color(color = 0xFF26C073),
    cardBackgroundBase = Color(color = 0xFF282A32),
    cardBackgroundActive = Color(color = 0xFF2C3747),
    noticeBase = Color(color = 0xFF3D5EFF),
    noticeDisable = Color(color = 0xFF5C5855),
    noticeOnBadge = Color(color = 0xFFFFFFFF),
    noticeCounterBadge = Color(color = 0xFF3D5EFF),
    searchBackground = Color(color = 0xFF282A32),
    mentionSuggestionsBackground = Color(color = 0xFF1B1B1D),
    indicatorYellow = Color(color = 0xFFFFCC00),
    indicatorPink = Color(color = 0xFFF458D2),
    indicatorPurple = Color(color = 0xFF7087FF),
    indicatorOrange = Color(color = 0xFFBD77EE),
    indicatorGreen = Color(color = 0xFF26C038),
    indicatorRed = Color(color = 0xFFFA3B7E),
    indicatorBlue = Color(color = 0xFF51ABFF),
    indicatorGrey = Color(color = 0xFF484848),
    chatHeaderBackground = Color(color = 0xFF282A32),
    divider = Color(color = 0xFF323234)
)

val LocalWorkspaceColorsPalette = staticCompositionLocalOf { WorkspaceColorsPalette() }
