#!/usr/bin/env node

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { basename } from "node:path";

const [datasetPath, overridesPath, outputPath] = process.argv.slice(2);

if (datasetPath == null || overridesPath == null || outputPath == null) {
  process.stderr.write(
    "Usage: generate_workspace_emoji_catalog.mjs " +
      "<emojibase.json> <emoji-shortcodes-overrides.data.ts> <output.tsv>\n",
  );
  process.exit(2);
}

function normalizeShortcode(value) {
  return value
    .trim()
    .toLowerCase()
    .replace(/^:+|:+$/g, "")
    .replace(/[\s-]+/g, "_")
    .replace(/[^a-z0-9_+]+/g, "")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function normalizeUnified(value) {
  return value
    .trim()
    .toLowerCase()
    .replace(/_/g, "-")
    .split("-")
    .filter(Boolean)
    .join("-");
}

function withoutEmojiVariation(value) {
  return normalizeUnified(value)
    .split("-")
    .filter((part) => part !== "fe0f")
    .join("-");
}

function decodeUnified(value) {
  const points = normalizeUnified(value)
    .split("-")
    .map((part) => Number.parseInt(part, 16));
  if (
    points.length === 0 ||
    points.some(
      (point) =>
        !Number.isFinite(point) ||
        point < 0 ||
        point > 0x10ffff ||
        (point >= 0xd800 && point <= 0xdfff),
    )
  ) {
    return null;
  }
  return String.fromCodePoint(...points);
}

function addAlias(aliasToUnified, aliasRaw, unifiedRaw) {
  const alias = normalizeShortcode(aliasRaw);
  const unified = normalizeUnified(unifiedRaw);
  if (alias.length === 0 || unified.length === 0) return;
  const values = aliasToUnified.get(alias) ?? new Set();
  values.add(unified);
  aliasToUnified.set(alias, values);
}

const datasetSource = readFileSync(datasetPath, "utf8");
const dataset = JSON.parse(datasetSource);
const aliasToUnified = new Map();

for (const [unified, aliasesRaw] of Object.entries(dataset)) {
  const aliases = Array.isArray(aliasesRaw) ? aliasesRaw : [aliasesRaw];
  for (const alias of aliases) {
    addAlias(aliasToUnified, alias, unified);
  }
}

const overridesSource = readFileSync(overridesPath, "utf8");
const overridesBody = overridesSource
  .split("ZULIP_SHORTCODE_TO_UNIFIED_OVERRIDES", 2)[1]
  ?.split("};", 1)[0];
if (overridesBody == null) {
  throw new Error("Zulip shortcode override map was not found");
}

const overridePattern = /^\s*([a-z0-9_+-]+):\s*"([0-9a-f-]+)",\s*$/gim;
let overrideCount = 0;
for (const match of overridesBody.matchAll(overridePattern)) {
  const alias = normalizeShortcode(match[1]);
  const unified = normalizeUnified(match[2]);
  if (alias.length === 0 || unified.length === 0) continue;
  aliasToUnified.set(alias, new Set([unified]));
  overrideCount += 1;
}
if (overrideCount === 0) {
  throw new Error("Zulip shortcode override map was empty");
}

const unicodeByShortcode = new Map();
for (const [alias, unifiedValues] of aliasToUnified) {
  const byBase = new Map();
  for (const unified of unifiedValues) {
    const base = withoutEmojiVariation(unified);
    if (base.length === 0) continue;
    const variants = byBase.get(base) ?? [];
    variants.push(unified);
    byBase.set(base, variants);
  }
  if (byBase.size !== 1) continue;
  const variants = byBase.values().next().value;
  const preferred =
    variants.find((variant) => variant.split("-").includes("fe0f")) ?? variants[0];
  const unicode = preferred == null ? null : decodeUnified(preferred);
  if (unicode != null) unicodeByShortcode.set(alias, unicode);
}

const datasetHash = createHash("sha256").update(datasetSource).digest("hex");
const overridesHash = createHash("sha256").update(overridesSource).digest("hex");
const lines = [
  "# Generated by tools/generate_workspace_emoji_catalog.mjs.",
  `# Dataset: ${basename(datasetPath)} sha256=${datasetHash}`,
  `# Overrides: ${basename(overridesPath)} sha256=${overridesHash}`,
  `# Entries: ${unicodeByShortcode.size}; Zulip overrides: ${overrideCount}`,
  ...[...unicodeByShortcode.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([shortcode, unicode]) => `${shortcode}\t${unicode}`),
  "",
];

writeFileSync(outputPath, lines.join("\n"), "utf8");
